### ISSUE TITLE
Regarding EnsembleStrategy loop 

### ISSUE THREAD

**Issue by minulislam** [joaorafaelm/freqtrade-heroku#1]
Hello,first of all thanks for your EnsembleStrategy.
And I need your help to understand something ..
In your EnsembleStrategyV1.py the code block
https://github.com/joaorafaelm/freqtrade-heroku/blob/7f465163e44afaf8caccc389e118d3036e442850/user_data/strategies/EnsembleStrategyV1.py#L164-L166
Here you use LOOP over strategy array..
How it make sense for sell_param sell_strategies value.. 
While your. https://github.com/joaorafaelm/freqtrade-heroku/blob/7f465163e44afaf8caccc389e118d3036e442850/user_data/strategies/EnsembleStrategy.py#L85-L87 
Code block looks perfect to me.  

The main point of the issue is should we comment (#)
https://github.com/joaorafaelm/freqtrade-heroku/blob/7f465163e44afaf8caccc389e118d3036e442850/user_data/strategies/EnsembleStrategyV1.py#L166 

this line ???

**Comment by joaorafaelm** [comment]
Hi @minulislam , yes you are correct, line 166 is not necessary, it is basically enforcing usage of all strategies to populate sell indicators... I removed it from the main strat but I forgot to remove it from the v1 strat...

**Comment by joaorafaelm** [comment]
should be ok now https://github.com/joaorafaelm/freqtrade-heroku/blob/master/user_data/strategies/EnsembleStrategyV1.py

**Comment by minulislam** [comment]
Many many thanks.  
And as I am not expert nor I know python.
I have few questions regarding this strategy...
The question is.. some of strategy need  startup_candle_count. Like your NostalgiaForInfinity series also need process_new_candle.. 
So the point is as I understand, we should put maximum number of candle count (few need 20-200 candle only ) . But you don't put any. And even some strategy doesn't need process_new_candle . ( While backtesting I saw different results for setting process_new_candle value true or false. And startup candle count enable and value 200-400)

**Comment by joaorafaelm** [comment]
hi @minulislam at this time the strat is experimental, I made some changes so that the code now runs well in dry live and test mode, but it is really slow. I'm working on it to make it faster and I'll take a look at other attributes that may or may not increase performance. Thanks for bringing this up, I'll make some tests and let you know
